### ISSUE TITLE
[BE] login error

### ISSUE THREAD

**Issue by leechan02** [42Nuts/Transcendence#81]
## ⚠️ 어떤 버그인가요 ?
login에서 server error 발생

## 📝 어떤 상황에서 발생하나요 ?
왜 로그인이 안되는지 모르겠음
그리고 환경변수 세팅이 안되어있다합니다. loginHTML?에서

## 💡 기대했던 동작

- [ ] 기대했던 정상적인 동작

##  📷 스크린샷
![image](https://github.com/42Nuts/Transcendence/assets/89778914/9c636a35-ee92-4084-aad2-ce94df0868c0)

**Comment by gitubanana** [comment]
스크린샷 부탁드립니다!

**Comment by leechan02** [comment]
@gitubanana 스크린샷 첨부했습니다

**Comment by gitubanana** [comment]
새로 깃 클론하니 해결됐네요~?
수고하셨습니당~!

**Comment by gitubanana** [comment]
아마도 뭔가가 남아 있어서 문제가 생긴 것 같네요.
